version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:latest  # latest 태그 사용
    container_name: dev-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  # Redis 캐시
  redis:
    image: redis:latest  # latest 태그 사용
    container_name: dev-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  # Spring Boot 애플리케이션
  app:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: dev-app
    ports:
      - "8080:8080"
    environment:
      # Spring 프로파일
      SPRING_PROFILES_ACTIVE: dev
      # 데이터베이스 설정
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Redis 설정
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      # 보안 설정
      JWT_SECRET: ${JWT_SECRET}
      # 로깅 설정 (CloudWatch용)
      LOGGING_FILE_NAME: /var/log/app/application.log
    volumes:
      # 로그 파일을 호스트와 공유 (CloudWatch Agent가 수집)
      - /var/log/tpt-app:/var/log/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

# 네트워크 정의
networks:
  app-network:
    driver: bridge

# 볼륨 정의
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local