name: ✨ 기능 요청
description: 새로운 기능이나 개선사항을 제안해주세요
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 기능 요청 가이드
        
        새로운 아이디어를 제안해주셔서 감사합니다! 기능을 효과적으로 구현할 수 있도록 자세한 정보를 작성해주세요.

  - type: textarea
    id: feature-description
    attributes:
      label: 🎯 기능 설명
      description: 원하는 기능에 대해 명확하고 간결하게 설명해주세요
      placeholder: 예) 사용자가 자신의 프로필 사진을 업로드하고 변경할 수 있는 기능
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 💪 동기 및 필요성
      description: 이 기능이 왜 필요한지, 어떤 문제를 해결하는지 설명해주세요
      placeholder: 현재 사용자 식별이 어려워 프로필 사진이 필요합니다. 사용자 경험 향상과 개인화를 위해 중요합니다.
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: 🏷️ 기능 유형
      description: 요청하는 기능의 유형을 선택해주세요
      options:
        - 새로운 API 엔드포인트
        - 기존 기능 개선
        - 보안 강화
        - 성능 최적화
        - 사용자 경험 개선
        - 개발자 경험 개선
        - 인프라 개선
        - 기타
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 📋 우선순위
      description: 이 기능의 우선순위를 선택해주세요
      options:
        - 높음 (중요하고 긴급)
        - 보통 (중요하지만 긴급하지 않음)
        - 낮음 (좋긴 하지만 필수는 아님)
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: 📝 상세 설명
      description: 기능의 동작 방식을 자세히 설명해주세요
      placeholder: |
        ## API 명세
        - POST /api/v1/users/{id}/profile-image
        - 파일 업로드 지원 (JPEG, PNG, 최대 5MB)
        - 이미지 리사이징 및 최적화 자동 처리
        
        ## 비즈니스 로직
        - 기존 프로필 이미지 자동 삭제
        - 이미지 검증 (크기, 형식, 내용)
        - S3 또는 로컬 저장소에 저장

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ 완료 조건
      description: 이 기능이 완료되었다고 볼 수 있는 조건들을 나열해주세요
      placeholder: |
        - [ ] 프로필 이미지 업로드 API 구현
        - [ ] 이미지 검증 로직 구현
        - [ ] 파일 저장 및 관리 시스템 구축
        - [ ] API 문서 업데이트
        - [ ] 단위 테스트 및 통합 테스트 작성
        - [ ] 보안 검토 완료

  - type: textarea
    id: technical-considerations
    attributes:
      label: 🔧 기술적 고려사항
      description: 구현 시 고려해야 할 기술적 요소들이 있다면 작성해주세요
      placeholder: |
        - 파일 저장 방식 (로컬 vs S3)
        - 이미지 처리 라이브러리 선택
        - 보안 고려사항 (파일 유형 검증, 악성 파일 차단)
        - 성능 최적화 (이미지 압축, CDN 사용)

  - type: textarea
    id: alternatives
    attributes:
      label: 🤔 대안 방안
      description: 이 기능 외에 고려해볼 수 있는 다른 방법이 있다면 설명해주세요
      placeholder: Gravatar 연동, SNS 프로필 이미지 가져오기 등

  - type: textarea
    id: additional-context
    attributes:
      label: 📚 추가 컨텍스트
      description: 참고할 만한 자료, 유사한 구현 사례, 관련 링크 등이 있다면 첨부해주세요
      placeholder: |
        - 관련 이슈: #123
        - 참고 문서: https://example.com
        - 유사 구현: 다른 프로젝트 링크

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 체크리스트
      description: 기능 요청 제출 전 확인사항
      options:
        - label: 기존 이슈에서 유사한 기능이 요청되지 않았는지 확인했습니다
          required: true
        - label: 기능의 목적과 필요성을 명확히 설명했습니다
          required: true
        - label: 구현 가능한 수준의 구체적인 요구사항을 포함했습니다
          required: true